language: node_js
node_js:
- node
services: mongodb
deploy:
  provider: lambda
  function_name: lambda test
  region: ap-southeast-1
  role: arn:aws:iam::0123456789012:role/lambda_basic_execution
  runtime: nodejs12.0
  handler_name: handler
  access_key_id:
    secure: 0yPiCJ9Aq02mpB9CgLjQVzBJZU5Y71tfGOBAsn0Q6uhAXrhdt6KX7gkQgSjxBXypAhN8uabOaxF5k4KJp7j4BBwouagM5muz/hyqN6R6uTsyaaYA+M17/OHjQ6FqYzPX6dUWVEUNN5PQ24dJDIpZBMxAzEHFVU4Z/TfeDwCIK19fv1zjs4E5L+N/ATVJZKULNV3p2Hox0QDzdLC1qJt4Fy0+uh/DwAC262pSG7o6ogv62pwnbM3tP6Cc1IhkBGl5MQdADLansRwFi3Nx5uGtB2YX7JAF1+YRamaMsKDzJLdoURot7QNtgzuAMNWcGYpxniVaenZBZZ0Mu3Yx2TwKU2vUQXXZPkPjsSFjStP/IZ5vmBkiPDXYavWQY/JYNtc8mIFOBzB8Y8O2V/kgW9FCY4Uv+oA+acSUDzcdsi+FZ9qrLGHWrVWvlOfQY/4Zkawav0cN8mjtECH6DpwibZ0ioYvWHKAiC7VD1phZjYUk37aVpAmYkNwT/9otniOfT4w9BNBswSRnhlHA5pmIS4gPa1Pmxgak7daxsdFnW7407R62YBIBJ2bpbdpg60LU4K4hqQWHh59XtaU7qglY1RlUg1HT23hGR7+E4uMD88EH/06twAulAlcdusj2AltYF2TVFpsYNm1gxqf0MR3RE6sUA42VJ1YqEXxLPkFVFLOAI/
