sudo: false
language: node_js
node_js:
- '12'
services: mongodb
cache:
  yarn: true
  directories:
  - "$HOME/google-cloud-sdk/"
env:
  global:
    secure: 2AscfAJeVI0I1aIsSQbcxpfvafXsfb0Fn2zHItXkL92JKOUE7nrHdp9pnn3fvcFLn1DSCvauqucU+7RPCpF1bVmBp9w+rfEpW3nMhHpLe7ivDSLf/QxtKw57Mv1zEFLCAUEydfqE5lujd5DZFE+NTdQEynuojhSAd/3d5PNCoEBdBPII10OHvvyzDSEh9N0wB9QtKGYGzoHf942jhmnectC0B0nCLGtWX2VMytI4SrjB1ksZd1sRkLFXWnJeUqv9Nt3arQAdoK3R3UTeQkD7xcLBqomiZxHfpaB4S8BZcIe2wjpnRmZonBydkjDvcLtAvjOYmFDzLJYrCr1EGKBhFastku9TRG8XJETEVoqAjZpAEf1/jSv394lLyJbs0JA4GYqq85GiDdojUjj4YGIkyIjXdGyYdOnb/SzSXoZgnsuDTc1ml1p9N90keKYZ5VRSwMGRmXjnTSxHMoiE5M/nHzx4Gr/Hfylk0lh0D78n9fUPK1vn7ilewP4cFTAanLu0QrHE0Vln0cRx0SD+5f4PKjxb955XGRQ7ENhsMEc5eKkp4tAZkvFwQeyvnO7Hrk3wOaakkwWCJwjMYIA628HlV5ntNObBAOGpMziZ5LrQwewrZdBcCP3ULAlbZNSxfmnXTQLix9SmsHfdaUwtrflJfvTt+yhUlECuP6+zk1Y4PKE=
install:
- npm install
script:
- npm test
before_deploy:
- openssl aes-256-cbc -K $encrypted_f8ef6066f5ff_key -iv $encrypted_f8ef6066f5ff_iv
  -in gcloud-service-key.json.enc -out gcloud-service-key.json -d
- gcloud auth activate-service-account --key-file gcloud-service-key.json
- gcloud config set project cs3219-pokedex
deploy:
- provider: script
  script:
  - gcloud beta functions deploy pokedex --source https://source.developers.google.com/projects/cs3219-pokedex/repos/github_lyskevin_pokedex/moveable-aliases/master/paths//
    --runtime nodejs12 --trigger-http --entry-point app --region asia-east2
  skip_cleanup: true
  on:
    branch: master
