sudo: false
language: node_js
node_js:
- '12'
services: mongodb
cache:
  yarn: true
  directories:
  - "$HOME/google-cloud-sdk/"
env:
  global:
    secure: h6uVZZBaHtdurN1PgmoYWYpfz+ISU9MGKK5pOpjO4NF8nAfAebJtrGHEaLN92DLuMvE42zA9O8i9duu02O3xzVYXBKIP3jI371u+UyGm1QKrvMsojtz4oXPZbr4BUf+uD4hwTdHgP2MxDGxEx4x7pANeL0aXSRYPe5oIk2Vj8j8YAzHgg1NbmgGz9zvJCKnpAsdvT9kMOLNos7CA2xpwY6ATuwSfHU9ngltFKv0+QFNz0mtzKv4BjH+G2zZ4j2f5HTthOOiVKTKW/QjV8aJpDcFiQV02Lo5984175d84/SgcM+LS3R892UZExlcIZjs5g/DauAUcUqiMU+ShfqY08ZuUyZuceH9h6dmTSWL7gnYSvS9TEvKrCdNlLr8kn3Hf+QpJVXnKIDM38t8Ph3tb9dZM+lfbxO+8v7CInEPGuO8fj18je6mN1e0hkaHuONOFTH+rWZQzqE0QzQ1rr8NKj1WmYUW5VNGuqLPlV+GypVAxFqMiN9vwpKbmU+N5Oo0aIdPOwb6ohKZVvQjjGN0O6ZpPP1fb7t1RFj8N4IWdrNw7Vxlb3Dn+BAFQMtZHgLHjZ69cEZ5MvFbTM1Km/Nyd5/1QOauQl5ppuoxDjRg/vLQlOctL2t7GpaiZBQtZc5snlOgiLjQU+dMcQBrzUAIm+qRRm8VxoM/yQrCZ8vYI0fA=
install:
- npm install
script:
- npm test
before_deploy:
- openssl aes-256-cbc -K $encrypted_f8ef6066f5ff_key -iv $encrypted_f8ef6066f5ff_iv
  -in gcloud-service-key.json.enc -out gcloud-service-key.json -d
- gcloud auth activate-service-account --key-file gcloud-service-key.json
- gcloud config set project cs3219-pokedex
deploy:
- provider: script
  script:
  - gcloud beta functions deploy pokedex --source https://source.developers.google.com/projects/cs3219-pokedex/repos/github_lyskevin_pokedex/moveable-aliases/master/paths//
    --runtime nodejs12 --trigger-http --entry-point app --region asia-east2
  skip_cleanup: true
  on:
    branch: master
