# Source: https://www.drzon.net/posts/automatic-deployments-to-google-cloud-functions-with-travis-ci/

# Use Dockerized infrastructure
sudo: false

# Use node_js environnement
language: node_js
node_js:
  - "12"

# Set up MongoDB
services: mongodb

# Cache Gcloud SDK between commands
cache:
  yarn: true
  directories:
  - "$HOME/google-cloud-sdk/"

env:
  global:


install:
  - npm install

script:
  - npm test

before_deploy:
  # use the decrypted service account credentials to authenticate the command line tool
  # get the encrypted variable names from travis cli: https://docs.travis-ci.com/user/encrypting-files/
  - openssl aes-256-cbc -K $encrypted_f8ef6066f5ff_key -iv $encrypted_f8ef6066f5ff_iv -in gcloud-service-key.json.enc -out gcloud-service-key.json -d
  - gcloud auth activate-service-account --key-file gcloud-service-key.json

  - gcloud config set project cs3219-pokedex

deploy:
  - provider: script
    script:
      # change PROJECT and REPO to the values from the cloud console: https://console.cloud.google.com/code/develop
      - gcloud beta functions deploy pokedex --source https://source.developers.google.com/projects/cs3219-pokedex/repos/github_lyskevin_pokedex/moveable-aliases/master/paths// --runtime nodejs12 --trigger-http --entry-point app --region asia-east2
    skip_cleanup: true
    on:
      branch: master
